// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceApiTier.Models;

#nullable disable

namespace ServiceApiTier.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621120311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceApiTier.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 11, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8540),
                            Description = "Customs import declaration for electronics",
                            Name = "Import Declaration"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 12, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8549),
                            Description = "Customs export declaration for machinery",
                            Name = "Export Declaration"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 13, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8550),
                            Description = "Transit documentation for goods in transit",
                            Name = "Transit Document"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 14, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8551),
                            Description = "Temporary storage authorization",
                            Name = "Temporary Storage"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 15, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8552),
                            Description = "Clearance certificate for imported goods",
                            Name = "Customs Clearance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 16, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8553),
                            Description = "Commercial invoice validation record",
                            Name = "Invoice Validation"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 17, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8554),
                            Description = "Certificate of origin documentation",
                            Name = "Certificate of Origin"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 18, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8555),
                            Description = "Customs duty payment confirmation",
                            Name = "Duty Payment"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 19, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8556),
                            Description = "Goods inspection report",
                            Name = "Inspection Report"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 20, 12, 3, 10, 951, DateTimeKind.Utc).AddTicks(8557),
                            Description = "Final release order for goods",
                            Name = "Release Order"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
