apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serviceapi-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serviceapi-service
            port:
              number: 80